### ISSUE TITLE
missing unity 2019.4.31f1

### ISSUE THREAD

**Issue by walksanatora** [neogeek/get-unity#27]
it can be downloaded with the urls 
    linux: https://download.unity3d.com/download_unity/bd5abf232a62/LinuxEditorInstaller/Unity.tar.xz
    mac: https://download.unity3d.com/download_unity/bd5abf232a62/MacEditorInstaller/Unity-2019.4.31f1.pkg
    win64: https://download.unity3d.com/download_unity/bd5abf232a62/Windows64EditorInstaller/UnitySetup64-2019.4.31f1.exe
I bring this specific version up because it is the latest used by VRchat

**Comment by neogeek** [comment]
Thanks for the heads up! My automation tools were no longer working, so I'm updating the repo to use GitHub Actions. Might take a few more days to get it finalized but that version should be in the next release!
